# training config
batch_size: 4
lr: 0.01
warmup_steps: 200
epochs: 50
lr_steps: [25, 40]

# dataset
# img_dir: '/home/twc/ddisk/coco128/images/train2017'
# label_dir: '/home/twc/ddisk/coco128/labels/train2017'
# classes: ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
#         'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
#         'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
#         'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
#         'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
#         'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
#         'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
#         'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
#         'hair drier', 'toothbrush']

classes: ['fire']
train_img_dir: '/home/twc/ddisk/fire_detection/data/fire_yolo/train'
train_label_dir: '/home/twc/ddisk/fire_detection/data/fire_yolo/train'
val_img_dir: '/home/twc/ddisk/fire_detection/data/fire_yolo/val'
val_label_dir: '/home/twc/ddisk/fire_detection/data/fire_yolo/val'